-- Atlas Daily seed data
-- This file is intentionally empty. Stories are now generated via the /submit page or /api/stories/generate endpoint.
-- To clear all existing seed data: DELETE FROM stories;
