name = "atlas-daily"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "atlas-daily-db"
database_id = "4b727b1b-6743-48a2-991a-98de63a9eb84"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "atlas-daily-storage"
